/**
 * Order Api
 * This is the order server api. 
 *
 * OpenAPI spec version: 1.0.0
 * Contact: richardcristhian94@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Product { 
    id?: string;
    productTypeId?: string;
    name: string;
    image: string;
}