/**
 * Order Api
 * This is the order server api. 
 *
 * OpenAPI spec version: 0.0.1
 * Contact: richardcristhian94@gmail.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */
import { Section } from './section';

export interface Table { 
    id?: string;
    number: number;
    description: string;
    section: Section;
}